# Generated by Django 3.1.5 on 2021-02-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='images',
            field=models.ImageField(upload_to='img/upload'),
        ),
    ]
